version: 2
enable-beta-ecosystems: true
updates:
  # - package-ecosystem: swift-package
  #   directory: /
  #   schedule:
  #     interval: weekly
  #   commit-message:
  #     prefix: 'deps: '

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'ci(Deps): '

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'ci(Deps): '
