name: Setup action for Swift library
description: Setup action for Swift library `dynamic-codable-kit`
inputs:
  cocoapods:
    description: Whether to setup for CocoaPods
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup swift
      uses: swift-actions/setup-swift@v1.15.0
      with:
        swift-version: '5.6'

    - name: Setup Xcode version
      if: inputs.cocoapods == 'true'
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: latest-stable

    - name: Setup Cocoapods
      if: inputs.cocoapods == 'true'
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Setup npm pacakges
      if:  steps.check_version_bump.outputs.release_type == ''
      run: npm install
