#if !canImport(ObjectiveC)
import XCTest

extension DynamicDecodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodableTests = [
        ("testArrayCastingToBoxTypeArray", testArrayCastingToBoxTypeArray),
        ("testArrayCastingToExistentialArray", testArrayCastingToExistentialArray),
        ("testCastingToBoxType", testCastingToBoxType),
        ("testCastingToExistential", testCastingToExistential),
        ("testDefaultCollectionCastingForSingleValue", testDefaultCollectionCastingForSingleValue),
        ("testDefaultCollectionCastingForSingleValueFailure", testDefaultCollectionCastingForSingleValueFailure),
        ("testDefaultCollectionDownCasting", testDefaultCollectionDownCasting),
        ("testDefaultCollectionDownCastingFailure", testDefaultCollectionDownCastingFailure),
        ("testDefaultDownCasting", testDefaultDownCasting),
        ("testDefaultDownCastingFailure", testDefaultDownCastingFailure),
        ("testDefaultOptionalDownCasting", testDefaultOptionalDownCasting),
        ("testDefaultOptionalDownCastingFailure", testDefaultOptionalDownCastingFailure),
        ("testOptionalCastingToBoxType", testOptionalCastingToBoxType),
        ("testOptionalCastingToExistential", testOptionalCastingToExistential),
        ("testSetCastingToBoxTypeSet", testSetCastingToBoxTypeSet),
    ]
}

extension DynamicDecodingCollectionContextBasedWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodingCollectionContextBasedWrapperTests = [
        ("testDecoding", testDecoding),
        ("testInvalidDataDecodingWithDefaultConfig", testInvalidDataDecodingWithDefaultConfig),
        ("testInvalidDataDecodingWithLossyConfig", testInvalidDataDecodingWithLossyConfig),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
    ]
}

extension DynamicDecodingCollectionDictionaryWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodingCollectionDictionaryWrapperTests = [
        ("testDecoding", testDecoding),
        ("testInvalidDataDecodingWithDefaultConfig", testInvalidDataDecodingWithDefaultConfig),
        ("testInvalidDataDecodingWithLossyConfig", testInvalidDataDecodingWithLossyConfig),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
    ]
}

extension DynamicDecodingCollectionWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodingCollectionWrapperTests = [
        ("testDecoding", testDecoding),
        ("testDecodingWithSet", testDecodingWithSet),
        ("testDynamicTypeDecodingWithSelfCodingKeyContext", testDynamicTypeDecodingWithSelfCodingKeyContext),
        ("testInvalidDataDecodingWithDefaultConfig", testInvalidDataDecodingWithDefaultConfig),
        ("testInvalidDataDecodingWithDefaultConfigWithSet", testInvalidDataDecodingWithDefaultConfigWithSet),
        ("testInvalidDataDecodingWithLossyConfig", testInvalidDataDecodingWithLossyConfig),
        ("testInvalidDataDecodingWithLossyConfigWithSet", testInvalidDataDecodingWithLossyConfigWithSet),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
        ("testInvalidDataDecodingWithThrowConfigWithSet", testInvalidDataDecodingWithThrowConfigWithSet),
        ("testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithDefaultConfig", testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithDefaultConfig),
        ("testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithLossyConfig", testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithLossyConfig),
        ("testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithThrowConfig", testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithThrowConfig),
    ]
}

extension DynamicDecodingContextBasedWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodingContextBasedWrapperTests = [
        ("testDecoding", testDecoding),
        ("testIdentifierKeyContextDecoding", testIdentifierKeyContextDecoding),
        ("testInvalidDataDecodingWithDefaultConfig", testInvalidDataDecodingWithDefaultConfig),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
        ("testOptionalDecoding", testOptionalDecoding),
    ]
}

extension DynamicDecodingContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodingContextTests = [
        ("testFallbackArrayDecoding", testFallbackArrayDecoding),
        ("testFallbackDecodingWithFallbackSucess", testFallbackDecodingWithFallbackSucess),
        ("testFallbackDecodingWithPrimarySucess", testFallbackDecodingWithPrimarySucess),
        ("testInvalidDataDecodingWithDefaultConfig", testInvalidDataDecodingWithDefaultConfig),
        ("testInvalidDataDecodingWithLossyConfig", testInvalidDataDecodingWithLossyConfig),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
    ]
}

extension DynamicDecodingDictionaryWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodingDictionaryWrapperTests = [
        ("testDecoding", testDecoding),
        ("testInvalidDataDecodingWithLossyConfig", testInvalidDataDecodingWithLossyConfig),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
    ]
}

extension DynamicDecodingWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicDecodingWrapperTests = [
        ("testDecoding", testDecoding),
        ("testDynamicTypeDecodingWithSelfCodingKeyContext", testDynamicTypeDecodingWithSelfCodingKeyContext),
        ("testInvalidDataDecodingWithDefaultConfig", testInvalidDataDecodingWithDefaultConfig),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
        ("testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithDefaultConfig", testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithDefaultConfig),
        ("testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithThrowConfig", testInvalidDataDynamicTypeDecodingWithSelfCodingKeyContextWithThrowConfig),
        ("testOptionalDecoding", testOptionalDecoding),
        ("testOptionalDynamicTypeDecodingWithSelfCodingKeyContext", testOptionalDynamicTypeDecodingWithSelfCodingKeyContext),
    ]
}

extension DynamicEncodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicEncodableTests = [
        ("testArrayEncoding", testArrayEncoding),
        ("testArrayEncodingFailure", testArrayEncodingFailure),
        ("testDynamicArrayEncoding", testDynamicArrayEncoding),
        ("testDynamicCollectionDictionaryEncoding", testDynamicCollectionDictionaryEncoding),
        ("testDynamicDictionaryEncoding", testDynamicDictionaryEncoding),
        ("testDynamicEncoding", testDynamicEncoding),
        ("testEmptyEncoding", testEmptyEncoding),
        ("testEncoding", testEncoding),
        ("testEncodingFailure", testEncodingFailure),
        ("testOptionalDynamicEncoding", testOptionalDynamicEncoding),
        ("testOptionalEmptyEncoding", testOptionalEmptyEncoding),
        ("testOptionalEncoding", testOptionalEncoding),
        ("testOptionalEncodingFailure", testOptionalEncodingFailure),
        ("testOptionalProviderEncoding", testOptionalProviderEncoding),
        ("testProviderArrayEncoding", testProviderArrayEncoding),
        ("testProviderEncoding", testProviderEncoding),
    ]
}

extension PathCodingKeyWrapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathCodingKeyWrapperTests = [
        ("testDecoding", testDecoding),
        ("testInvalidDataDecodingWithDefaultConfig", testInvalidDataDecodingWithDefaultConfig),
        ("testInvalidDataDecodingWithThrowConfig", testInvalidDataDecodingWithThrowConfig),
        ("testInvalidOptionalPathCodingKeyWrapperDecoding", testInvalidOptionalPathCodingKeyWrapperDecoding),
        ("testInvalidPathCodingKeyWrapperDecoding", testInvalidPathCodingKeyWrapperDecoding),
        ("testOptionalDecoding", testOptionalDecoding),
        ("testOptionalPathCodingKeyWrapperDecoding", testOptionalPathCodingKeyWrapperDecoding),
        ("testPathCodingKeyWrapperDecoding", testPathCodingKeyWrapperDecoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DynamicDecodableTests.__allTests__DynamicDecodableTests),
        testCase(DynamicDecodingCollectionContextBasedWrapperTests.__allTests__DynamicDecodingCollectionContextBasedWrapperTests),
        testCase(DynamicDecodingCollectionDictionaryWrapperTests.__allTests__DynamicDecodingCollectionDictionaryWrapperTests),
        testCase(DynamicDecodingCollectionWrapperTests.__allTests__DynamicDecodingCollectionWrapperTests),
        testCase(DynamicDecodingContextBasedWrapperTests.__allTests__DynamicDecodingContextBasedWrapperTests),
        testCase(DynamicDecodingContextTests.__allTests__DynamicDecodingContextTests),
        testCase(DynamicDecodingDictionaryWrapperTests.__allTests__DynamicDecodingDictionaryWrapperTests),
        testCase(DynamicDecodingWrapperTests.__allTests__DynamicDecodingWrapperTests),
        testCase(DynamicEncodableTests.__allTests__DynamicEncodableTests),
        testCase(PathCodingKeyWrapperTests.__allTests__PathCodingKeyWrapperTests),
    ]
}
#endif
