name: "Run CocoaPods Linting"

on:
  workflow_call:

jobs:
  # Lint podspec with latest Xcode and Swift version
  cocoapods:
    name: Run CocoaPods Linting on latest macos
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check should proceed running steps
      id: precondition
      uses: ./.github/actions/condition
      with:
        files: |
          Sources/**/*.swift
          Tests/**/*
          *.podspec
          .github/actions/setup/action.yml
          .github/workflows/cocoapods.yml

    - name: Setup repository
      if: steps.precondition.outputs.proceed == 'true'
      uses: ./.github/actions/setup

    - name: Run tests
      if: steps.precondition.outputs.proceed == 'true'
      run: npm run pod-lint
