name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  workflow_dispatch:
    inputs:
      release:
        description: Create release
        required: false
        type: boolean

concurrency:
  group: ci/cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    if: github.event_name != 'workflow_dispatch'
    uses: ./.github/workflows/codeql-analysis.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  swift-package-test:
    name: Run Swift Package Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup swift
    - uses: swift-actions/setup-swift@v1.15.0
      with:
        swift-version: '5.6'

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Setup npm pacakges
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Swift Coverage Report
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: maxep/spm-lcov-action@0.3.1
      with:
        file-format: lcov
        output-file: ./coverage.lcov

    - name: Codecov upload
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  cocoapods-test:
    name: Run CocoaPods Tests
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup swift
    - uses: swift-actions/setup-swift@v1.15.0
      with:
        swift-version: '5.6'

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.4.1
      with:
        xcode-version: latest-stable
    
    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Setup npm pacakges
      run: npm install

    - name: Run tests
      run: npm run pod-lint

  ci:
    name: Check if release needed
    if: github.event_name != 'workflow_dispatch'
    needs: [analyze, swift-package-test, cocoapods-test]
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check_version_bump.outputs.release_type != '' }}

    steps:
    - name: Check version bump
      id: check_version_bump
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ github.token }}
        default_bump: false
        dry_run: true

  cd:
    name: Build and Publish
    if: (github.event_name == 'push' && needs.ci.outputs.release == 'true') || (github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true')
    needs: [ci, analyze, swift-package-test, cocoapods-test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Setup npm pacakges
      run: npm install

    # - name: Conventional Changelog Action
    #   id: conventional_changelog
    #   uses: TriPSs/conventional-changelog-action@v3
    #   with:
    #     github-token: ${{ github.token }}
    #     git-message: 'chore(CHANGELOG): update for {version}'
    #     git-user-name: ${{ github.actor }}
    #     git-user-email: soumya.mahunt@gmail.com
    #     skip-version-file: true
    #     release-count: 0
    #     config-file-path: '.github/config/config.js'
    #     pre-commit: '.github/config/pre_commit_hook.js'

    - name: Build package
      if: steps.conventional_changelog.outputs.skipped == 'false'
      run: npm run build

    - name: Build package documentation
      if: steps.conventional_changelog.outputs.skipped == 'false'
      run: npm run build-doc

    - name: Build package documentation for hosting
      if: steps.conventional_changelog.outputs.skipped == 'false'
      run: npm run serve-doc

    # - name: Create GitHub Release
    #   if: steps.conventional_changelog.outputs.skipped == 'false'
    #   uses: ncipollo/release-action@v1
    #   with:
    #     token: ${{ github.token }}
    #     tag: ${{ steps.conventional_changelog.outputs.tag }}
    #     body: ${{ steps.conventional_changelog.outputs.changelog }}
    #     artifacts: '**/*.doccarchive'
